# Generated by Django 2.2.12 on 2021-01-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectDotu', '0003_auto_20210110_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_turn',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
